# Site settings

title: Yalun Su # Title of your site
email: yalunsu@gmail.com # Your contant email

description: > Yalun Su
# this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yalunsu.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:       # Replace this with your Twitter username
linkedin_username:    suyalun  # Replace this with your LinkedIn username
github_username:      yalunsu  # Replace this with your GitHub username
google_plus_username:   # Replace this with your Google+ username
facebook_username:    ysu92  # Replace this with your Facebook username
dribbble_username:      # Replace this with your Dribbble username

# Build settings
markdown: kramdown
